version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=jbu_catalog
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - 3308:3306