<?php
    include "connect-to-db.php";
    $start_year = 2022; // change this to a session var or HTTP post or whatever
    $odd_year_courses = array();
    $even_year_courses = array();
    $spring_courses = array();
    $fall_courses = array();
    
    $sql = "select * from majors_minors_classes where course_code like 'CS-%'";
    $cs_courses = fetchCourses($sql, $connect);

    foreach ($cs_courses as $key => $value) {
        $course = new Course();
        $course->parse_sql_arry($value);
        if ($course->offered_main_campus_fall) {
            $fall_courses[] = $course;
        }
        if ($course->offered_main_campus_spring) {
            $spring_courses[] = $course;
        }
        if ($course->offered_main_campus_even_year) {
            $even_year_courses[] = $course;
        }
        if ($course->offered_main_campus_odd_year) {
            $odd_year_courses[] = $course;
        }

        $course->printCourse();
        echo "---------------------------------------------<br>";
    }

    class Course {
        // Properties
        public $course_code;
        public $course_title;
        public $credits_count;
        public $description;
        public $location;
        public $honors;
        public $offered_main_campus_fall;
        public $offered_main_campus_spring;
        public $offered_main_campus_even_year;
        public $offered_main_campus_odd_year;

        // Methods
        public function parse_sql_arry($sql_array) {
            // Takes an array from the response array generated by fetchCourses and constructs a course object.
            $this->course_code = $sql_array["course_code"];
            $this->course_title = $sql_array["course_title"];
            $this->credits_count = $sql_array["credits_count"];
            $this->description = $sql_array["description"];
            $this->location = $sql_array["location"];
            $this->honors = $sql_array["honors"];
            $this->offered_main_campus_fall= $sql_array["offered_main_campus_fall"];
            $this->offered_main_campus_spring = $sql_array["offered_main_campus_spring"];
            $this->offered_main_campus_even_year= $sql_array["offered_main_campus_even_year"];
            $this->offered_main_campus_odd_year = $sql_array["offered_main_campus_odd_year"];
        }

        public function printCourse() {
            echo "Course Code: " . $this->course_code . "<br>";
            echo "Course Title: " . $this->course_title . "<br>";
            echo "Credits Count: " . $this->credits_count . "<br>";
            echo "Description: " . $this->description . "<br>";
            echo "Location: " . $this->location . "<br>";
            if ($this->honors == 1) {
                echo "Honors<br>";
            }
            echo "Offered in Fall: " . ($this->offered_main_campus_fall ? "Yes" : "No") . "<br>";
            echo "Offered in Spring: " . ($this->offered_main_campus_spring ? "Yes" : "No") . "<br>";
            echo "Offered in Even Year: " . ($this->offered_main_campus_even_year ? "Yes" : "No") . "<br>";
            echo "Offered in Odd Year: " . ($this->offered_main_campus_odd_year ? "Yes" : "No") . "<br>";
        }
    }

function fetchCourses($sql, $connect) {
        $courses = array();
        $result = $connect->query($sql);
        while ($row = $result->fetch_array()) {
            $courses[] = array(
                "course_code" => $row['course_code'],
                "course_title" => $row['course_title'],
                "credits_count" => $row['credits_count'],
                "description" => $row['description'],
                "location" => $row["location"],
                "honors" => $row["honors"],
                "offered_main_campus_fall"=>$row["offered_main_campus_fall"],
                "offered_main_campus_spring"=>$row["offered_main_campus_spring"],
                "offered_main_campus_even_year"=>$row["offered_main_campus_even_year"],
                "offered_main_campus_odd_year"=>$row["offered_main_campus_odd_year"]);
        }
        return $courses;
    }
?>